# Generated by Django 5.2.3 on 2025-08-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
