# Generated by Django 5.2.3 on 2025-08-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_specialoffer_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
